### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [alpheccar/HPDF#10]
Hi,

I prefer to use libraries that were added to stackage, as that provides free QA to the maintainer of the package and catches problems earlier that would otherwise hit me as a user. It’s also a soft prerequisite for having a program enter Debian.

It’s simple to do: http://www.stackage.org/authors

Greetings,
Joachim

**Comment by alpheccar** [comment]
Hi. Thanks. It is is on my to do list. I just need to find some time.

**Comment by alpheccar** [comment]
Done.
