### ISSUE TITLE
Exception because of missing glyphlist.txt

### ISSUE THREAD

**Issue by limick** [alpheccar/HPDF#20]
I get an exception as follows:

`/home/limick/testproject/.stack-work/install/x86_64-linux-nopie/lts-7.24/8.0.1/share/x86_64-linux-ghc-8.0.1/HPDF-1.5.0/Encodings/glyphlist.txt: openBinaryFile: does not exist (No such file or directory) `

The file does indeed not exist at that path, and the compiled executable was copied to the server without it. What I don't understand is why the path is hardcoded. It's valid on the build machine, but not on the server. If the path was relative, I would know where to put the file.
Any guidance or documentation on how to make my executable find this file?
The commit used was: 9b1cb50bdef8b02443e9a0037ad5c6b9e31a9179

**Comment by limick** [comment]
Seems to be an issue with [relocatable packages](https://github.com/haskell/cabal/issues/462).

**Comment by tfausak** [comment]
I ran into this issue today. I was able to fix it by copying all the data files into a directory (like `/opt/HPDF`) and then setting the `HPDF_datadir` environment variable to that directory.
