### ISSUE TITLE
createPDFRawImage should take Integers, not Floats

### ISSUE THREAD

**Issue by nomeata** [alpheccar/HPDF#8]
Because it rounds them, which is dangerous for something that is used to index into the vector of pixels. Assume the user misses it a bit and the width gets rounded into the wrong direction, then all the rows of the image will be shifted.

It would also make it clear that this not only specifies the size of the image (when drawn unscaled) in pt, but also that this specifies the layout of the pixel vector.

**Comment by alpheccar** [comment]
I agree. Next commit will contain this fix too.

**Comment by nomeata** [comment]
Thanks for the fix and upload. Did you accidentally not bump according to the PVP, or do you generally not follow the PVP? (The upload temporarily broke my package at https://github.com/entropia/tip-toi-reveng/issues/123)

**Comment by alpheccar** [comment]
Sorry for this. I have not been rigorous at all in my handling of version numbers. I'll read the PVP page and try to follow it.

**Comment by nomeata** [comment]
No worries. I’m also not always following it precisely, but “obvious API breakage ⇒ bump the second component” usually cuts it.
