### ISSUE TITLE
Provide a faster createPDFRawImage

### ISSUE THREAD

**Issue by nomeata** [alpheccar/HPDF#9]
Hi,

it seems that in my application createPDFRawImage accounts for more than 40% of the runtime. Judging from the code, there are a lot of bytes being moved around, to create the final ByteString.

I would appreciate to have a variant of `createPDFRawImage` that takes a `ByteString` in the final form directly, so that I can create that in the format right away.

Thanks,
Joachim

**Comment by alpheccar** [comment]
I reworked a little bit the image API. Now there are two functions : createPDFRawImageFromARGB and the new createPDFRawImageFromBytestrings. The new function can take a filter in parameters so it may be possible to directly used a compressed byte string. But I have not yet tested at all this new function. Also I assume that for some filters it may be needed to pass additional parameters to the PDF. I need to read the PDF spec again. So, in short : the simple filter like LZWDecod, FlateDecodeand RunLengthDecode should work I think.

The byte strings must be using packed 24 bits RGB pixels. I may allow more flexibility with color space in a future version when I find some time to test this function.

I have committed all the changes. I'll put them on package when it is a bit more tested.

**Comment by nomeata** [comment]
Thanks, the speedup was quite noticeable! (13s to 2.3s)! Now the code spends 40% of the time compressing the final PDF (which, uncompressed, would be 250MB and compressed is 500kb). I guess compressing each image individually, using one of the filters you mention, might be more efficient and still yield similar (or even better) compression results.

**Comment by nomeata** [comment]
> might be more efficient and still yield similar (or even better) compression results.

Nah, no real change here, it seems. Nevertheless, thanks!
